//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ontap3
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongVien
    {
        public string MaPV { get; set; }
        public string HoTen { get; set; }
        public string GioiTinh { get; set; }
        public string SoDienThoai { get; set; }
        public DateTime NgayVaoLam { get; set; }
        public byte[] HinhAnhPV { get; set; }
        public Nullable<decimal> Luong { get; set; }
        public Nullable<bool> LoaiPV { get; set; }
    }
}
